/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.authz.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RefreshTokenEntry service. Represents a row in the &quot;ATHZ_RefreshTokenEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.authz.model.impl.RefreshTokenEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.authz.model.impl.RefreshTokenEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RefreshTokenEntry
 * @generated
 */
@ProviderType
public interface RefreshTokenEntryModel extends BaseModel<RefreshTokenEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a refresh token entry model instance should use the {@link RefreshTokenEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this refresh token entry.
	 *
	 * @return the primary key of this refresh token entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this refresh token entry.
	 *
	 * @param primaryKey the primary key of this refresh token entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this refresh token entry.
	 *
	 * @return the uuid of this refresh token entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this refresh token entry.
	 *
	 * @param uuid the uuid of this refresh token entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the refresh token ID of this refresh token entry.
	 *
	 * @return the refresh token ID of this refresh token entry
	 */
	public long getRefreshTokenId();

	/**
	 * Sets the refresh token ID of this refresh token entry.
	 *
	 * @param refreshTokenId the refresh token ID of this refresh token entry
	 */
	public void setRefreshTokenId(long refreshTokenId);

	/**
	 * Returns the user name of this refresh token entry.
	 *
	 * @return the user name of this refresh token entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this refresh token entry.
	 *
	 * @param userName the user name of this refresh token entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the token of this refresh token entry.
	 *
	 * @return the token of this refresh token entry
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this refresh token entry.
	 *
	 * @param token the token of this refresh token entry
	 */
	public void setToken(String token);

	/**
	 * Returns the expiry date of this refresh token entry.
	 *
	 * @return the expiry date of this refresh token entry
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this refresh token entry.
	 *
	 * @param expiryDate the expiry date of this refresh token entry
	 */
	public void setExpiryDate(Date expiryDate);

	/**
	 * Returns the issued date of this refresh token entry.
	 *
	 * @return the issued date of this refresh token entry
	 */
	public Date getIssuedDate();

	/**
	 * Sets the issued date of this refresh token entry.
	 *
	 * @param issuedDate the issued date of this refresh token entry
	 */
	public void setIssuedDate(Date issuedDate);

	/**
	 * Returns the refreshed date of this refresh token entry.
	 *
	 * @return the refreshed date of this refresh token entry
	 */
	public Date getRefreshedDate();

	/**
	 * Sets the refreshed date of this refresh token entry.
	 *
	 * @param refreshedDate the refreshed date of this refresh token entry
	 */
	public void setRefreshedDate(Date refreshedDate);

}